- hosts: local
  tasks:
    - name: Remove all existing containers (force)
      shell: docker rm -f $(docker ps -aq)
      ignore_errors: true

    - name: Pull Docker image
      docker_image:
        name: valmikdocker7/spe_mini_calculator
        tag: latest
        source: pull

    - name: Run calculator container
      docker_container:
        name: calculator
        image: valmikdocker7/spe_mini_calculator:latest
        state: started
        detach: true
        restart_policy: no