- hosts: local
  tasks:
    - name: Pull Docker image
      command: docker pull <your-dockerhub-username>/scientific-calculator:latest

    - name: Run calculator container
      command: docker run -it --rm <your-dockerhub-username>/scientific-calculator:latest